# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_cadastro.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Tela_Cadastro(object):
    def setupUi(self, Tela_Cadastro):
        Tela_Cadastro.setObjectName("Tela_Cadastro")
        Tela_Cadastro.resize(800, 600)
        Tela_Cadastro.setFixedSize(800, 600)
        font = QtGui.QFont()
        font.setFamily("Lucida Sans Unicode")
        Tela_Cadastro.setFont(font)
        self.centralwidget = QtWidgets.QWidget(Tela_Cadastro)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(230, 100, 351, 381))
        self.textBrowser.setObjectName("textBrowser")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(340, 50, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.toolButton = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton.setGeometry(QtCore.QRect(230, 40, 41, 41))
        self.toolButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/back_12955.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon)
        self.toolButton.setIconSize(QtCore.QSize(28, 28))
        self.toolButton.setObjectName("toolButton")
        self.botao_salvar = QtWidgets.QPushButton(self.centralwidget)
        self.botao_salvar.setGeometry(QtCore.QRect(360, 390, 80, 30))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans Unicode")
        font.setPointSize(9)
        self.botao_salvar.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/save_file_disk_open_searsh_loading_clipboard_1513.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botao_salvar.setIcon(icon1)
        self.botao_salvar.setIconSize(QtCore.QSize(16, 16))
        self.botao_salvar.setObjectName("botao_salvar")
        self.e_mail = QtWidgets.QLineEdit(self.centralwidget)
        self.e_mail.setGeometry(QtCore.QRect(290, 245, 221, 30))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans Unicode")
        font.setPointSize(9)
        self.e_mail.setFont(font)
        self.e_mail.setObjectName("e_mail")
        self.nome = QtWidgets.QLineEdit(self.centralwidget)
        self.nome.setGeometry(QtCore.QRect(290, 170, 221, 30))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans Unicode")
        font.setPointSize(9)
        self.nome.setFont(font)
        self.nome.setObjectName("nome")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(290, 220, 56, 19))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans Unicode")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(290, 145, 53, 19))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans Unicode")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.senha = QtWidgets.QLineEdit(self.centralwidget)
        self.senha.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.senha.setMaxLength(15)
        self.senha.setGeometry(QtCore.QRect(290, 320, 221, 30))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans Unicode")
        font.setPointSize(9)
        self.senha.setFont(font)
        self.senha.setObjectName("senha")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(290, 295, 56, 19))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans Unicode")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        Tela_Cadastro.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Tela_Cadastro)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        Tela_Cadastro.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Tela_Cadastro)
        self.statusbar.setObjectName("statusbar")
        Tela_Cadastro.setStatusBar(self.statusbar)

        self.retranslateUi(Tela_Cadastro)
        QtCore.QMetaObject.connectSlotsByName(Tela_Cadastro)

    def retranslateUi(self, Tela_Cadastro):
        _translate = QtCore.QCoreApplication.translate
        Tela_Cadastro.setWindowTitle(_translate("Tela_Cadastro", "Cadastrar usuário"))
        self.label_3.setText(_translate("Tela_Cadastro", "CADASTRO"))
        self.botao_salvar.setText(_translate("Tela_Cadastro", "SALVAR"))
        self.label_2.setText(_translate("Tela_Cadastro", "E-mail:"))
        self.label.setText(_translate("Tela_Cadastro", "Nome:"))
        self.label_4.setText(_translate("Tela_Cadastro", "Senha:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Tela_Cadastro = QtWidgets.QMainWindow()
    ui = Ui_Tela_Cadastro()
    ui.setupUi(Tela_Cadastro)
    Tela_Cadastro.show()
    sys.exit(app.exec_())
